---
- name: Get {{ key }} key from machine
  command: "grep -i {{ key }} {{ key_file }}"
  register: found_key
  become: "{{ true if not key_local else false }}"
  check_mode: false
  changed_when: false
  delegate_to: "{{ wg_client_config_storage_host if key_local }}"
  no_log: true

- name: Set {{ key }} key as fact
  set_fact:
    found_key: '{{ found_key.stdout | regex_search(key | string + "\s?=\s?([a-zA-Z0-9+/]*=)", "\1") | first }}'
  no_log: true

- name: Set {{ key }} key as fact
  set_fact: >
    {{ key_var }}={{ found_key }}
  no_log: true
