---
- name: Stop wireguard service
  ansible.builtin.systemd:
    name: wg-quick@wg0
    state: stopped
  become: true
  listen: restart wireguard service wg0

- name: Start wireguard service
  ansible.builtin.systemd:
    name: wg-quick@wg0
    enabled: true
    state: started
  become: true
  listen: restart wireguard service wg0

- name: Stop wireguard service
  ansible.builtin.systemd:
    name: wg-quick@wg1
    state: stopped
  become: true
  listen: restart wireguard service wg1

- name: Start wireguard service
  ansible.builtin.systemd:
    name: wg-quick@wg1
    enabled: true
    state: started
  become: true
  listen: restart wireguard service wg1
