---
- name: Restart wireguard service {{ wireguard_iffname }}
  block:
    - name: Stop wireguard service {{ wireguard_iffname }}
      ansible.builtin.systemd:
        name: "wg-quick@{{ wireguard_iffname }}"
        state: started
      become: true
      ignore_unreachable: true
      listen: restart wireguard service

    - name: Start wireguard service
      ansible.builtin.systemd:
        name: "wg-quick@{{ wireguard_iffname }}"
        enabled: true
        state: reloaded
      become: true
      listen: restart wireguard service
